2024-09-12T18:58:25,489 Using pip 24.2 from c:\Users\pooja\MLproject\venv\Lib\site-packages\pip (python 3.11)
2024-09-12T18:58:25,489 Non-user install because site-packages writeable
2024-09-12T18:58:25,537 Created temporary directory: C:\Users\pooja\AppData\Local\Temp\pip-build-tracker-iuuh_rdd
2024-09-12T18:58:25,537 Initialized build tracking at C:\Users\pooja\AppData\Local\Temp\pip-build-tracker-iuuh_rdd
2024-09-12T18:58:25,537 Created build tracker: C:\Users\pooja\AppData\Local\Temp\pip-build-tracker-iuuh_rdd
2024-09-12T18:58:25,537 Entered build tracker: C:\Users\pooja\AppData\Local\Temp\pip-build-tracker-iuuh_rdd
2024-09-12T18:58:25,550 Created temporary directory: C:\Users\pooja\AppData\Local\Temp\pip-install-uwp0asep
2024-09-12T18:58:25,553 Created temporary directory: C:\Users\pooja\AppData\Local\Temp\pip-ephem-wheel-cache-p0z9u361
2024-09-12T18:58:25,553 1 location(s) to search for versions of requirements-txt:
2024-09-12T18:58:25,553 * https://pypi.org/simple/requirements-txt/
2024-09-12T18:58:25,553 Fetching project page and analyzing links: https://pypi.org/simple/requirements-txt/
2024-09-12T18:58:25,553 Getting page https://pypi.org/simple/requirements-txt/
2024-09-12T18:58:25,553 Found index url https://pypi.org/simple/
2024-09-12T18:58:25,759 Could not fetch URL https://pypi.org/simple/requirements-txt/: 404 Client Error: Not Found for url: https://pypi.org/simple/requirements-txt/ - skipping
2024-09-12T18:58:25,759 Skipping link: not a file: https://pypi.org/simple/requirements-txt/
2024-09-12T18:58:25,759 Given no hashes to check 0 links for project 'requirements-txt': discarding no candidates
2024-09-12T18:58:25,759 ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
2024-09-12T18:58:25,759 HINT: You are attempting to install a package literally named "requirements.txt" (which cannot exist). Consider using the '-r' flag to install the packages listed in requirements.txt
2024-09-12T18:58:25,775 Remote version of pip: 24.2
2024-09-12T18:58:25,775 Local version of pip:  24.2
2024-09-12T18:58:25,791 Was pip installed by pip? False
2024-09-12T18:58:25,791 ERROR: No matching distribution found for requirements.txt
2024-09-12T18:58:25,801 Exception information:
2024-09-12T18:58:25,801 Traceback (most recent call last):
2024-09-12T18:58:25,801   File "c:\Users\pooja\MLproject\venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
2024-09-12T18:58:25,801     self._add_to_criteria(self.state.criteria, r, parent=None)
2024-09-12T18:58:25,801   File "c:\Users\pooja\MLproject\venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 174, in _add_to_criteria
2024-09-12T18:58:25,801     raise RequirementsConflicted(criterion)
2024-09-12T18:58:25,801 pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('requirements.txt')
2024-09-12T18:58:25,801 
2024-09-12T18:58:25,801 During handling of the above exception, another exception occurred:
2024-09-12T18:58:25,801 
2024-09-12T18:58:25,801 Traceback (most recent call last):
2024-09-12T18:58:25,801   File "c:\Users\pooja\MLproject\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
2024-09-12T18:58:25,801     result = self._result = resolver.resolve(
2024-09-12T18:58:25,801                             ^^^^^^^^^^^^^^^^^
2024-09-12T18:58:25,801   File "c:\Users\pooja\MLproject\venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
2024-09-12T18:58:25,801     state = resolution.resolve(requirements, max_rounds=max_rounds)
2024-09-12T18:58:25,801             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-12T18:58:25,801   File "c:\Users\pooja\MLproject\venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 399, in resolve
2024-09-12T18:58:25,801     raise ResolutionImpossible(e.criterion.information)
2024-09-12T18:58:25,801 pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('requirements.txt'), parent=None)]
2024-09-12T18:58:25,801 
2024-09-12T18:58:25,801 The above exception was the direct cause of the following exception:
2024-09-12T18:58:25,801 
2024-09-12T18:58:25,801 Traceback (most recent call last):
2024-09-12T18:58:25,801   File "c:\Users\pooja\MLproject\venv\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
2024-09-12T18:58:25,801     status = _inner_run()
2024-09-12T18:58:25,801              ^^^^^^^^^^^^
2024-09-12T18:58:25,801   File "c:\Users\pooja\MLproject\venv\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
2024-09-12T18:58:25,801     return self.run(options, args)
2024-09-12T18:58:25,801            ^^^^^^^^^^^^^^^^^^^^^^^
2024-09-12T18:58:25,801   File "c:\Users\pooja\MLproject\venv\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
2024-09-12T18:58:25,801     return func(self, options, args)
2024-09-12T18:58:25,801            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-12T18:58:25,801   File "c:\Users\pooja\MLproject\venv\Lib\site-packages\pip\_internal\commands\install.py", line 379, in run
2024-09-12T18:58:25,801     requirement_set = resolver.resolve(
2024-09-12T18:58:25,801                       ^^^^^^^^^^^^^^^^^
2024-09-12T18:58:25,801   File "c:\Users\pooja\MLproject\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 104, in resolve
2024-09-12T18:58:25,801     raise error from e
2024-09-12T18:58:25,801 pip._internal.exceptions.DistributionNotFound: No matching distribution found for requirements.txt
2024-09-12T18:58:25,822 Removed build tracker: 'C:\\Users\\pooja\\AppData\\Local\\Temp\\pip-build-tracker-iuuh_rdd'
2024-09-12T18:59:37,563 Using pip 24.2 from c:\Users\pooja\MLproject\venv\Lib\site-packages\pip (python 3.11)
2024-09-12T18:59:37,563 Non-user install because site-packages writeable
2024-09-12T18:59:37,594 Created temporary directory: C:\Users\pooja\AppData\Local\Temp\pip-build-tracker-9pz923qz
2024-09-12T18:59:37,594 Initialized build tracking at C:\Users\pooja\AppData\Local\Temp\pip-build-tracker-9pz923qz
2024-09-12T18:59:37,594 Created build tracker: C:\Users\pooja\AppData\Local\Temp\pip-build-tracker-9pz923qz
2024-09-12T18:59:37,594 Entered build tracker: C:\Users\pooja\AppData\Local\Temp\pip-build-tracker-9pz923qz
2024-09-12T18:59:37,594 Created temporary directory: C:\Users\pooja\AppData\Local\Temp\pip-install-79wdu9qc
2024-09-12T18:59:37,594 Created temporary directory: C:\Users\pooja\AppData\Local\Temp\pip-ephem-wheel-cache-a9ntt3at
2024-09-12T18:59:37,610 Created temporary directory: C:\Users\pooja\AppData\Local\Temp\pip-unpack-y8cf8ss8
2024-09-12T18:59:37,645 Remote version of pip: 24.2
2024-09-12T18:59:37,645 Local version of pip:  24.2
2024-09-12T18:59:37,645 Was pip installed by pip? False
2024-09-12T18:59:37,645 Removed build tracker: 'C:\\Users\\pooja\\AppData\\Local\\Temp\\pip-build-tracker-9pz923qz'
